name = CSEU-Theme Page layout
description = CSEU-Theme Page mobile first with 1 column layout.
preview = preview.png
template = page-layout

; Regions
regions[branding]       = Branding
regions[header]         = Header
regions[navigation]     = Navigation

regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar

regions[footer]         = Footer
regions[footer_first]   = Footer First
regions[footer_second]  = Footer Second
regions[footer_third]   = Footer Third
regions[footer_fourth]  = Footer Fourth
regions[footer_fifth]   = Footer Fifth
regions[footer_sixth]   = Footer Sixth

; Stylesheets
stylesheets[all][] = css/layouts/page/page.layout.css



