name = CSEU-Theme Frontpage layout
description = CSEU-Theme Frontpage mobile first with 1 column layout.
preview = preview.png
template = frontpage-layout

; Regions
regions[branding]       = Branding
regions[header]         = Header
regions[navigation]     = Navigation

regions[highlighted]    = Highlighted
regions[help]           = Help
regions[featured]       = Featured
regions[slider]         = Slider
regions[news]           = News
regions[disruptive]     = Disruptive
regions[misc]           = Miscellaneous

regions[footer]         = Footer
regions[footer_bottom]  = Footer Bottom

; Stylesheets
stylesheets[all][] = css/layouts/frontpage/frontpage.layout.css


